<?xml version="1.0"?>

<robot name="quake_description" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="$(find quake_description)/xacro/const.xacro"/>
    <xacro:include filename="$(find quake_description)/xacro/materials.xacro"/>
    <xacro:include filename="$(find quake_description)/xacro/leg.xacro"/>
    <xacro:include filename="$(find quake_description)/xacro/gazebo.xacro"/>
    <xacro:include filename="$(find quake_description)/xacro/arm.xacro"/>

    
    <!-- Rollover Protection mode will add an additional stick on the top, use "true" or "false" to switch it. -->
    <xacro:property name="rolloverProtection" value="false"/>

    <!-- Debug mode will hung up the robot, use "true" or "false" to switch it. -->
    <!-- <xacro:if value="$(arg DEBUG)">
        <link name="world"/>
        <joint name="base_static_joint" type="fixed">
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <parent link="world"/>
            <child link="base"/>
        </joint>
    </xacro:if> 

    <link name="base">
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <box size="0.001 0.001 0.001"/>
            </geometry>
        </visual>
    </link>

    <joint name="floating_base" type="fixed">
        <origin rpy="0 0 0" xyz="0.1 0.1 0"/>
        <parent link="base"/>
        <child link="trunk"/>
    </joint> -->

    <link name="trunk">
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <mesh filename="package://quake_description/meshes/trunk.STL" scale="1 1 1"/>
            </geometry>
            <material name="gold"/>
        </visual>
        <!-- <collision>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <mesh filename="package://quake_description/meshes/trunk.STL" scale="1 1 1"/>
            </geometry>
        </collision> -->
        <inertial>
            <origin rpy="0 0 0" xyz="${trunk_com_x} ${trunk_com_y} ${trunk_com_z}"/>
            <mass value="${trunk_mass}"/>
            <inertia
                ixx="${trunk_ixx}" ixy="${trunk_ixy}" ixz="${trunk_ixz}"
                iyy="${trunk_iyy}" iyz="${trunk_iyz}"
                izz="${trunk_izz}"/>  
        </inertial>
    </link>

    <xacro:if value="${(rolloverProtection == 'true')}">
        <joint name="stick_joint" type="fixed">
            <parent link="trunk"/>
            <child link="stick_link"/>
            <origin rpy="0 0 0" xyz="${0.18} 0 ${stick_length/2.0+0.08}"/>
        </joint>

        <link name="stick_link">
            <visual>
                <geometry>
                    <cylinder length="${stick_length}" radius="${stick_radius}"/>
                </geometry>
                <origin rpy="0 0 0" xyz="0 0 0"/>
                <material name="white"/>
            </visual>
            <collision>
                <geometry>
                    <cylinder length="${stick_length}" radius="${stick_radius}"/>
                </geometry>
                <origin rpy="0 0 0" xyz="0 0 0"/>
            </collision>
            <inertial>
                <mass value="${stick_mass}"/>
                <inertia
                    ixx="${stick_mass / 2.0 * (stick_radius*stick_radius)}" ixy="0.0" ixz="0.0"
                    iyy="${stick_mass / 12.0 * (3*stick_radius*stick_radius + stick_length*stick_length)}" iyz="0.0"
                    izz="${stick_mass / 12.0 * (3*stick_radius*stick_radius + stick_length*stick_length)}"/>                   
            </inertial>
        </link>
    </xacro:if> 

    <joint name="imu_joint" type="fixed">
        <parent link="trunk"/>
        <child link="imu_link"/>
        <origin rpy="0 0 0" xyz="0 0 0"/>
    </joint>

    <link name="imu_link">
        <inertial>
            <mass value="0.001"/>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.000001" iyz="0" izz="0.0001"/>
        </inertial>
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <box size="0.001 0.001 0.001"/>
            </geometry>
            <material name="red"/>
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <box size=".001 .001 .001"/>
            </geometry>
        </collision>
    </link>

    <xacro:include filename="$(find velodyne_description)/urdf/HDL-32E.xacro"/>
    <HDL-32E parent="trunk" name="lidar_link" topic="/trunk_lidar" hz="20" samples="220" gpu="false">
      <origin rpy="0 0 3.14" xyz="0.42 0 0.1"/>
    </HDL-32E>

    <xacro:include filename="$(find realsense_ros_gazebo)/xacro/depthcam.xacro"/>
    <xacro:include filename="$(find realsense_ros_gazebo)/xacro/tracker.xacro"/>
     <xacro:realsense_d435 sensor_name="d435" parent_link="trunk" rate="20">
        <origin rpy="0 0 0 " xyz="0.45 0 0.01"/>
    </xacro:realsense_d435>

    <!-- <xacro:arg name="use_nominal_extrinsics" default="false" />
    <xacro:include filename="$(find realsense2_description)/urdf/_d435i.urdf.xacro"/>
    <xacro:sensor_d435i parent="trunk" use_nominal_extrinsics="$(arg use_nominal_extrinsics)">
        <origin xyz="0.45 0 0.01" rpy="0 0 0.0"/>
    </xacro:sensor_d435i> -->


    <xacro:leg name="FR" mirror="-1" mirror_STL="False" front_hind="1" front_hind_STL="True">
        <origin rpy="0 0 0" xyz="${leg_offset_x} ${-leg_offset_y} 0"/>
    </xacro:leg>

    <xacro:leg name="FL" mirror="1" mirror_STL="True" front_hind="1" front_hind_STL="True">
        <origin rpy="0 0 0" xyz="${leg_offset_x} ${leg_offset_y} 0"/>
    </xacro:leg>

    <xacro:leg name="RR" mirror="-1" mirror_STL="False" front_hind="-1" front_hind_STL="False">
        <origin rpy="0 0 0" xyz="${-leg_offset_x} ${-leg_offset_y} 0"/>
    </xacro:leg>

    <xacro:leg name="RL" mirror="1" mirror_STL="True" front_hind="-1" front_hind_STL="False">
        <origin rpy="0 0 0" xyz="${-leg_offset_x} ${leg_offset_y} 0"/>
    </xacro:leg>

    <xacro:arm parent="trunk">
         <origin xyz="0.17 0 0.0975" rpy="0 0 3.141592653" />
         <!-- <origin xyz="0.215755098636628 0.404242003580351 -0.191270550095696 " rpy="0 0 0" /> -->

         
    </xacro:arm>

    <gazebo>
        <plugin name="p3d_base_controller" filename="libgazebo_ros_p3d.so">
          <alwaysOn>true</alwaysOn>
          <updateRate>200.0</updateRate>
          <bodyName>trunk</bodyName>
          <topicName>ground_truth/state</topicName>
          <gaussianNoise>0.0</gaussianNoise>
          <frameName>world</frameName>
          <xyzOffsets>0 0 0</xyzOffsets>
          <rpyOffsets>0 0 0</rpyOffsets>
        </plugin>
      </gazebo>

</robot>
